dataset_csv: data/metalog_bmi_13k.csv
dataset_name: "metalog_bmi_13k"
outcome_colname: bmi
ml_methods:
  - glmnet
  - rf
  - xgbTree
kfold: 2
ncores: 4
nseeds: 100
find_feature_importance: false
hyperparams:
